apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: {{ .Values.appservice.type }}
  selector:
    app:  {{ .Values.deploymentname.app}}
  ports:
    - protocol: TCP
      port: {{.Values.appservice.port}}
      targetPort: {{ .Values.appservice.targetport}}
