apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deploymentname.app }}
  name: {{ .Values.deploymentname.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.deploymentname.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.deploymentname.app }}
    spec:
      imagePullSecrets:
        - name: gcr-io
      containers:
        - image: {{ .Values.appimage.repository}}
          name: app
          env:
             - name: REDIS_HOST
               value: redis-service
          imagePullPolicy: Always
---
